In [24]:
import numpy as np
import pandas as pd

df = pd.read_excel('Lab Session Data.xlsx', sheet_name=0)

A = df[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].to_numpy()
C = df['Payment (Rs)'].to_numpy()

C = C.reshape(-1, 1)

dimensionality = A.shape[1]
print(f"Dimensionality of the vector space: {dimensionality}")

num_vectors = A.shape[0]
print(f"Number of vectors in the vector space: {num_vectors}")

rank_A = np.linalg.matrix_rank(A)
print(f"Rank of Matrix A: {rank_A}")

A_pseudo_inv = np.linalg.pinv(A)

X = A_pseudo_inv @ C

print("\nMatrix A:")
print(A)

print("\nMatrix C:")
print(C)

print("\nPseudo-Inverse of A:")
print(A_pseudo_inv)

print("\nCost of each product available for sale (Matrix X):")
print(X)


Dimensionality of the vector space: 3
Number of vectors in the vector space: 10
Rank of Matrix A: 3

Matrix A:
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Matrix C:
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]

Pseudo-Inverse of A:
[[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]

Cost of each product available for sale (Matrix X):
[[ 1.]
 [55.]
 [18.]]
